/**
 * Curated Design Presets for TrailPoster Studio
 * Instant 1-click styling combinations inspired by minimalist fine-art posters
 */

export const PRESET_THEMES = [
  {
    id: 'transparent_clean',
    name: 'Trasparente Puro',
    description: 'Sfondo 100% trasparente (PNG Alpha) ideale per grafica e fotomontaggi',
    config: {
      bgType: 'transparent',
      bgColor: 'transparent',
      textColor: '#ffffff',
      trackColor: '#14b8a6',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Outfit',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.25,
      showTopo: true,
      topoOpacity: 0.18,
      contourFade: 24,
      contourEdgeFade: 12,
      showElevationChart: false,
    },
  },
  {
    id: 'transparent_ink',
    name: 'Inchiostro Trasparente',
    description: 'Traccia e testi neri su sfondo trasparente per stampa su carta/tessuto',
    config: {
      bgType: 'transparent',
      bgColor: 'transparent',
      textColor: '#18181b',
      trackColor: '#09090b',
      trackWidth: 5.2,
      trackOpacity: 1.0,
      trackGlow: false,
      fontFamily: 'Cinzel',
      showBorder: true,
      borderStyle: 'corners',
      borderOpacity: 0.35,
      showTopo: true,
      topoOpacity: 0.16,
      contourFade: 20,
      contourEdgeFade: 10,
      showElevationChart: false,
    },
  },
  {
    id: 'nordic_minimal',
    name: 'Nordic Minimal',
    description: 'Ardesia grafite scuro con traccia verde menta neon',
    config: {
      bgType: 'solid',
      bgColor: '#16181e',
      bgGradient: 'linear-gradient(135deg, #16181e 0%, #232733 100%)',
      textColor: '#f8fafc',
      trackColor: '#14b8a6',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Outfit',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.15,
      showTopo: true,
      topoOpacity: 0.15,
      contourFade: 25,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'monochrome_dark',
    name: 'Monochrome Dark',
    description: 'Nero profondo con traccia e scritte bianco puro',
    config: {
      bgType: 'solid',
      bgColor: '#0c0d10',
      bgGradient: 'linear-gradient(135deg, #0c0d10 0%, #1a1c24 100%)',
      textColor: '#ffffff',
      trackColor: '#ffffff',
      trackWidth: 4.5,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'JetBrains Mono',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.2,
      showTopo: true,
      topoOpacity: 0.12,
      contourFade: 22,
      contourEdgeFade: 12,
      elevationStyle: 'fill',
    },
  },
  {
    id: 'alpine_gold',
    name: 'Alpine Gold',
    description: 'Antracite scuro con traccia e dettagli oro metallico',
    config: {
      bgType: 'solid',
      bgColor: '#181614',
      bgGradient: 'linear-gradient(135deg, #181614 0%, #282420 100%)',
      textColor: '#fef3c7',
      trackColor: '#f59e0b',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Playfair Display',
      showBorder: true,
      borderStyle: 'double',
      borderOpacity: 0.3,
      dividerIcon: 'diamond',
      showTopo: true,
      topoOpacity: 0.14,
      contourFade: 24,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'vintage_alpine',
    name: 'Vintage Alpine',
    description: 'Carta crema calda con traccia espresso e serif classico',
    config: {
      bgType: 'solid',
      bgColor: '#f4ebd0',
      bgGradient: 'linear-gradient(135deg, #f4ebd0 0%, #e6dab8 100%)',
      textColor: '#291e16',
      trackColor: '#3d2516',
      trackWidth: 5.5,
      trackOpacity: 1.0,
      trackGlow: false,
      fontFamily: 'Cinzel',
      showBorder: true,
      borderStyle: 'vintage',
      borderOpacity: 0.35,
      dividerIcon: 'compass',
      showTopo: true,
      topoOpacity: 0.14,
      contourFade: 22,
      contourEdgeFade: 10,
      elevationStyle: 'line',
    },
  },
  {
    id: 'midnight_cyber',
    name: 'Midnight Cyber',
    description: 'Notte profonda con traccia viola elettrico fluorescente',
    config: {
      bgType: 'solid',
      bgColor: '#0a0a10',
      bgGradient: 'linear-gradient(135deg, #0a0a10 0%, #181428 100%)',
      textColor: '#f5f3ff',
      trackColor: '#a855f7',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Space Grotesk',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.25,
      dividerIcon: 'dots',
      showTopo: true,
      topoOpacity: 0.16,
      contourFade: 26,
      contourEdgeFade: 14,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'crimson_peak',
    name: 'Crimson Peak',
    description: 'Grafite carbone con traccia rosso cremisi fiammante',
    config: {
      bgType: 'solid',
      bgColor: '#131418',
      bgGradient: 'linear-gradient(135deg, #131418 0%, #221c22 100%)',
      textColor: '#ffffff',
      trackColor: '#f43f5e',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Inter',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.2,
      dividerIcon: 'mountain',
      showTopo: true,
      topoOpacity: 0.15,
      contourFade: 25,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'dolomite_stone',
    name: 'Dolomite Stone',
    description: 'Grigio calcare dolomitico con traccia azzurro cielo',
    config: {
      bgType: 'solid',
      bgColor: '#1a1f29',
      bgGradient: 'linear-gradient(135deg, #1a1f29 0%, #252e3d 100%)',
      textColor: '#f0f9ff',
      trackColor: '#38bdf8',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Outfit',
      showBorder: true,
      borderStyle: 'double',
      borderOpacity: 0.2,
      dividerIcon: 'mountain',
      showTopo: true,
      topoOpacity: 0.16,
      contourFade: 24,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'forest_trail',
    name: 'Forest Trail',
    description: 'Verde foresta alpina profondo con traccia lime luminoso',
    config: {
      bgType: 'solid',
      bgColor: '#0a1a14',
      bgGradient: 'linear-gradient(135deg, #0a1a14 0%, #142e24 100%)',
      textColor: '#ecfdf5',
      trackColor: '#84cc16',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Outfit',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.2,
      dividerIcon: 'mountain',
      showTopo: true,
      topoOpacity: 0.16,
      contourFade: 25,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'tokyo_neon',
    name: 'Tokyo Neon',
    description: 'Notte metropolitana con traccia ciano fluorescente',
    config: {
      bgType: 'solid',
      bgColor: '#08121e',
      bgGradient: 'linear-gradient(135deg, #08121e 0%, #0e2238 100%)',
      textColor: '#ecfeff',
      trackColor: '#06b6d4',
      trackWidth: 5.0,
      trackOpacity: 1.0,
      trackGlow: true,
      fontFamily: 'Space Grotesk',
      showBorder: true,
      borderStyle: 'corners',
      borderOpacity: 0.3,
      dividerIcon: 'dots',
      showTopo: true,
      topoOpacity: 0.16,
      contourFade: 26,
      contourEdgeFade: 12,
      elevationStyle: 'gradient',
    },
  },
  {
    id: 'archival_white',
    name: 'Archival White (Stampa)',
    description: 'Carta museale bianco puro con traccia inchiostro nero fine',
    config: {
      bgType: 'solid',
      bgColor: '#fafaf9',
      bgGradient: 'linear-gradient(135deg, #fafaf9 0%, #f0f0ee 100%)',
      textColor: '#1c1917',
      trackColor: '#0c0a09',
      trackWidth: 5.2,
      trackOpacity: 1.0,
      trackGlow: false,
      fontFamily: 'Cinzel',
      showBorder: true,
      borderStyle: 'classic',
      borderOpacity: 0.3,
      dividerIcon: 'line',
      showTopo: true,
      topoOpacity: 0.12,
      contourFade: 20,
      contourEdgeFade: 10,
      elevationStyle: 'line',
    },
  },
];
